options:
  site_name:                       
    type: string               
    description: Name of service shown in login screens and UI.
    default: "Mattermost"
  port:
    type: int
    description: Listen port
    default: 80
