options:
  site_name:                       
    type: string               
    description: Name of service shown in login screens and UI.
    default: "Mattermost"
  fqdn:                       
    type: string               
    description: Fqdn of mattermost server to use
    default: "mattermost.example.com"
  port:
    type: int
    description: Nginx listen port
    default: 80
    
